jwt:
    secret: jwt.secret
    sessionTime: 86400
server:
    port: 8080
spring:
    jackson:
        date-format: io.realworld.backend.rest.swagger.RFC3339DateFormat
        serialization:
            WRITE_DATES_AS_TIMESTAMPS: false
springfox:
    documentation:
        swagger:
            v2:
                path: /api-docs
