spring:
    datasource:
        driverClassName: org.h2.Driver
        password: password
        url: jdbc:h2:file:/Users/hmuludiki/git/realworld-backend-spring-ddd/data/demo
        username: sa
    h2:
        console:
            enabled: true
    jpa:
        database-platform: org.hibernate.dialect.H2Dialect
        defer-datasource-initialization: true
        hibernate:
            ddl-auto: update
        show-sql: true

